-- 최댓값 구하기
SELECT DATETIME FROM ANIMAL_INS ORDER BY DATETIME DESC LIMIT 1;
-- 최솟값 구하기
SELECT DATETIME FROM ANIMAL_INS ORDER BY DATETIME LIMIT 1;
-- 동물 수 구하기
SELECT COUNT(ANIMAL_ID) as count FROM ANIMAL_INS;
-- 중복 제거하기
SELECT COUNT(DISTINCT NAME) as count FROM ANIMAL_INS WHERE NOT NAME = "NULL"; 
